### ISSUE TITLE
bonzai-example runtime error index out of range

### ISSUE THREAD

**Issue by coopernetes** [rwxrob/bonzai-example#2]
Running the example main cmd, getting the following runtime error:

```shell
$ go run ./cmd/bonzai-example
NAME
       example - an example of Bonzai composite command tree

SYNOPSIS
       example COMMAND

COMMANDS
       help         - display help similar to man page format
       conf         - manage conf in /home/tom/.cache/bonzai-example/config.yaml
       var          - cache variables in /home/tom/.cache/bonzai-example/vars
       B|notbar|bar
       own         
       pkgexample  
       baz         

DESCRIPTION
2022/10/02 17:10:36 runtime error: index out of range [1] with length 1
exit status 1
```

With `Z.AllowPanic = true` and the full (?) stack trace:

```diff
diff --git a/cmd/bonzai-example/main.go b/cmd/bonzai-example/main.go
index b3503ad..6b90513 100644
--- a/cmd/bonzai-example/main.go
+++ b/cmd/bonzai-example/main.go
@@ -3,7 +3,13 @@
 
 package main
 
-import example "github.com/rwxrob/bonzai-example"
+import (
+       example "github.com/rwxrob/bonzai-example"
+       Z "github.com/rwxrob/bonzai/z"
+)
 
 // tree grown from branch
-func main() { example.Cmd.Run() }
+func main() {
+       Z.AllowPanic = true
+       example.Cmd.Run()
+}
```

```shell
$ go run ./cmd/bonzai-example
NAME
       example - an example of Bonzai composite command tree

...
DESCRIPTION
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/rwxrob/to.Dedented({0xc00029cae0, 0x4})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/to@v0.6.0/to.go:167 +0x1f5
github.com/rwxrob/bonzai/z.Blocks({0xc00028ec00?, 0xc00012dbe8?})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/bonzai@v0.14.1/z/mark.go:128 +0x6bd
github.com/rwxrob/bonzai/z.Mark({0xc00028ec00?, 0xc000014018?})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/bonzai@v0.14.1/z/mark.go:287 +0x38
github.com/rwxrob/bonzai/z.PrintMark({0xc00028ec00?, 0x7c3bbc?})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/bonzai@v0.14.1/z/mark.go:351 +0x1e
github.com/rwxrob/help.ForTerminal(0xae2320, {0x7a5837, 0x3})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/help@v0.5.0/help.go:254 +0x6da
github.com/rwxrob/help.glob..func1(0xae2e80, {0xc000016220?, 0x0?, 0x0?})
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/help@v0.5.0/help.go:83 +0x107
github.com/rwxrob/bonzai/z.(*Cmd).Run(0xae2320)
        /home/tom/.local/share/go/pkg/mod/github.com/rwxrob/bonzai@v0.14.1/z/cmd.go:333 +0x486
main.main()
        /home/tom/repos/github.com/rwxrob/bonzai-example/cmd/bonzai-example/main.go:14 +0x27
exit status 2
```

I poked around the various repos involved but couldn't pin down the issue.

**Comment by coopernetes** [comment]
Here's a quick and dirty patch in https://github.com/rwxrob/to 

```diff
diff --git a/to.go b/to.go
index e5c096e..b3ba391 100644
--- a/to.go
+++ b/to.go
@@ -188,6 +186,9 @@ func Prefixed(in, pre string) string {
 func Dedented(in string) string {
 	isblank := regexp.MustCompile(`^\s*$`)
 	lines := Lines(in)
+	if len(lines) == 1 && isblank.MatchString(lines[0]) {
+		return ""
+	}
 	var n int
 	for len(lines[n]) == 0 || isblank.MatchString(lines[n]) {
 		n++
diff --git a/to_test.go b/to_test.go
index a12be25..3e77bf2 100644
--- a/to_test.go
+++ b/to_test.go
@@ -117,6 +117,12 @@ func ExampleDedent_accidental_Chop() {
 	// "foo\nar"
 }
 
+func ExampleDedent_single_blank_line() {
+	fmt.Printf("%q\n", to.Dedented("    \n"))
+	// Output:
+	// ""
+}
+
 func ExampleIndentation() {
 	fmt.Println(to.Indentation("    some"))
 	fmt.Println(to.Indentation("  some"))

```

**Comment by rwxrob** [comment]
Thanks so much. Just seeing this now. Added and closed.
